/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peminjaman_buku_perpustakaan;

import java.awt.Component;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author nullomicron
 */
public class Peminjaman extends javax.swing.JFrame {

  /**
   * Creates new form peminjaman
   */
    
  public Statement st;
  public ResultSet rs;
  public DefaultTableModel tabModel;
  public String pinjam;
  public String kembali;
  Connection con = Koneksi.Koneksi();
  DaftarBuku d = new DaftarBuku();
  Informasi i = new Informasi();
  
  public Peminjaman() {
    initComponents();
    tampilIdBuku();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cIdBuku = new javax.swing.JComboBox<>();
        btnLihatDaftar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dTglPinjam = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtJudulBuku = new javax.swing.JTextField();
        txtTahun = new javax.swing.JTextField();
        txtNamaPengarang = new javax.swing.JTextField();
        btnPinjam = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(490, 420));
        setSize(new java.awt.Dimension(381, 315));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cIdBuku.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Kode Buku" }));
        cIdBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cIdBukuActionPerformed(evt);
            }
        });
        getContentPane().add(cIdBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 230, 30));

        btnLihatDaftar.setFont(new java.awt.Font("URW Bookman L", 1, 10)); // NOI18N
        btnLihatDaftar.setForeground(new java.awt.Color(51, 0, 0));
        btnLihatDaftar.setText("LIHAT DAFTAR BUKU");
        btnLihatDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLihatDaftarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLihatDaftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 160, 30));

        jLabel1.setFont(new java.awt.Font("DejaVu Sans Condensed", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setText("SILAHKAN LIHAT DAFTAR BUKU TERLEBIH DAHULU");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 480, 20));

        jLabel2.setFont(new java.awt.Font("DejaVu Sans Condensed", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setText("DAN PILIH KODE BUKU YANG INGIN DIPINJAM!!");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 450, 26));

        jLabel3.setFont(new java.awt.Font("Yrsa SemiBold", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 51));
        jLabel3.setText("ID BUKU");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 118, -1, -1));

        jLabel4.setFont(new java.awt.Font("Yrsa SemiBold", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 51));
        jLabel4.setText("JUDUL BUKU");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 161, -1, -1));

        jLabel5.setFont(new java.awt.Font("Yrsa SemiBold", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 51));
        jLabel5.setText("NAMA PENGARANG");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 247, -1, -1));

        dTglPinjam.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dTglPinjamPropertyChange(evt);
            }
        });
        getContentPane().add(dTglPinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 230, 30));

        jLabel6.setFont(new java.awt.Font("Yrsa SemiBold", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 51));
        jLabel6.setText("TAHUN TERBIT");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 204, 144, -1));

        jLabel7.setFont(new java.awt.Font("Yrsa SemiBold", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 51));
        jLabel7.setText("TANGGAL PEMINJAMAN");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 290, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 51));
        jLabel8.setText(":");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 123, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 153));
        jLabel9.setText(":");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 166, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 51));
        jLabel10.setText(":");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 209, -1, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 51));
        jLabel11.setText(":");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 252, -1, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 51));
        jLabel12.setText(":");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 295, -1, -1));

        txtJudulBuku.setEditable(false);
        getContentPane().add(txtJudulBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 230, -1));

        txtTahun.setEditable(false);
        getContentPane().add(txtTahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 230, -1));

        txtNamaPengarang.setEditable(false);
        getContentPane().add(txtNamaPengarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 230, -1));

        btnPinjam.setFont(new java.awt.Font("URW Bookman L", 1, 12)); // NOI18N
        btnPinjam.setForeground(new java.awt.Color(51, 0, 0));
        btnPinjam.setText("PINJAM");
        btnPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPinjamActionPerformed(evt);
            }
        });
        getContentPane().add(btnPinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, -1, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/peminjaman_buku_perpustakaan/maxresdefault.jpg"))); // NOI18N
        jLabel14.setText("jLabel14");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -330, 720, 910));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, -1, -1));

        setSize(new java.awt.Dimension(710, 430));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cIdBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cIdBukuActionPerformed
        // TODO add your handling code here:
        tampilData();
    }//GEN-LAST:event_cIdBukuActionPerformed

    private void btnLihatDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLihatDaftarActionPerformed
        // TODO add your handling code here:
        judul();
        tampilkanData();
        d.setVisible(true);
    }//GEN-LAST:event_btnLihatDaftarActionPerformed

    private void btnPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPinjamActionPerformed
        // TODO add your handling code here:
        pengembalian();
        i.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPinjamActionPerformed

    private void dTglPinjamPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dTglPinjamPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_dTglPinjamPropertyChange

  public void pengembalian() {
      SimpleDateFormat fTanggal = new SimpleDateFormat("dd MMMM yyyy");
      int lama = 3;
      Date tgl = dTglPinjam.getDate();
      Calendar calTambah = Calendar.getInstance();
      
      calTambah.setTime(tgl);
      calTambah.add(Calendar.DAY_OF_MONTH, lama);
      
      i.lblKembali.setText(fTanggal.format(calTambah.getTime()));
      i.judul.setText(txtJudulBuku.getText());
  }
  
  public void tampilIdBuku() {
      try {
          st = con.createStatement();
          rs = st.executeQuery("SELECT id_buku FROM tb_buku");
          
          while (rs.next()) {
              cIdBuku.addItem(rs.getString("id_buku"));
          }
      } catch(SQLException e) {
          
      }
  }
  
  public void tampilData() {
      try {
          st = con.createStatement();
          rs = st.executeQuery("SELECT judul,tahun,pengarang FROM tb_buku WHERE id_buku = '" + cIdBuku.getSelectedItem() + "'");
          
          while (rs.next()) {
              Object[] data = new Object[3];
              data[0] = rs.getString(1);
              data[1] = rs.getString(2);
              data[2] = rs.getString(3);
              
              txtJudulBuku.setText((String) data[0]);
              txtTahun.setText((String) data[1]);
              txtNamaPengarang.setText((String) data[2]);
          }
      } catch(SQLException e) {
          
      }
  }
  
  public void sesuaikanKolom() {
	        //cara untuk menyesuaikan kolom dari tabel adalah mengambil
	        // lebar kolom yang ada kemudian sesuaikan
	        TableColumnModel modelKolom = d.tbBuku.getColumnModel();

	        for (int kol = 0; kol < modelKolom.getColumnCount(); kol++) {
	            int lebarKolomMax = 0;
	            for (int baris = 0; baris < d.tbBuku.getRowCount(); baris++) {
	                TableCellRenderer rend = d.tbBuku.getCellRenderer(baris, kol);
	                Object nilaiTablel = d.tbBuku.getValueAt(baris, kol);
	                Component comp = rend.getTableCellRendererComponent(d.tbBuku, nilaiTablel, false, false, baris, kol);
	                lebarKolomMax = Math.max(comp.getPreferredSize().width, lebarKolomMax);
	            }//akhir for baris
	            TableColumn kolom = modelKolom.getColumn(kol);
	            kolom.setPreferredWidth(lebarKolomMax);
	        }//akhir for kolom
    }
  
    public void judul() {
        Object[] judul = {
            "ID Buku","Judul","Tahun","Pengarang"
        };
        tabModel = new DefaultTableModel(null, judul);
        d.tbBuku.setModel(tabModel);
    }
    
   public void tampilkanData() {
        try {
            st = con.createStatement();
            tabModel.getDataVector().removeAllElements();
            tabModel.fireTableDataChanged();
            rs = st.executeQuery("SELECT * FROM tb_buku");
            
            while (rs.next()) {
                Object[] data = {
                    rs.getString("id_buku"),
                    rs.getString("judul"),
                    rs.getString("tahun"),
                    rs.getString("pengarang"),
                };
                
                tabModel.addRow(data);
                sesuaikanKolom();
            }
            
        } catch(SQLException e) {
            
        }
        
    }
  
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /*
     * Set the Nimbus look and feel
     */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the
     * default look and feel. For details see
     * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /*
     * Create and display the form
     */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Peminjaman().setVisible(true);
      }
    });
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLihatDaftar;
    private javax.swing.JButton btnPinjam;
    private javax.swing.JComboBox<String> cIdBuku;
    private com.toedter.calendar.JDateChooser dTglPinjam;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtJudulBuku;
    private javax.swing.JTextField txtNamaPengarang;
    private javax.swing.JTextField txtTahun;
    // End of variables declaration//GEN-END:variables
}
